Qa axis
StickFunFight/AssistRecruitment pull request #22
Opened 2020-05-11 07:54 UTC by StickFunFight

2020-05-11 11:31 UTC, MarvinVissers approved these changes

2020-05-11 13:25 UTC, MarvinVissers approved these changes
Die nieuwe code is echt mooi

2020-05-12 11:54 UTC, wereldjes requested changes

2020-05-12 11:54 UTC, wereldjes commented on functions/datalayer/AxisDatabase.php
> +                                       WHERE AxisID = %d",$AxisName, $AxisStatus,$AxisID);
dit NOOIT doen. 
Maak gebruik van prepared statements !
dit maakt de code vulnerable voor SQL INJECTION

2020-05-12 11:54 UTC, wereldjes commented on functions/datalayer/CategoryDatabase.php
> +                $query = sprintf("UPDATE categorie SET categorieStatus = 'Archived' WHERE categorieID = %d", $cID);
Prepared statement gebruiken

2020-05-12 11:54 UTC, wereldjes commented on functions/datalayer/ContactDB.php
> +<?php
prepared statements

2020-05-12 11:54 UTC, wereldjes commented on functions/datalayer/CustomerDB.php
prepared statements

2020-05-12 11:54 UTC, wereldjes commented on functions/datalayer/DepartmentDB.php
> +<?php
prepared statements

2020-05-12 11:54 UTC, wereldjes commented on functions/datalayer/ScanDB.php
> +<?php
prepared statements

2020-05-12 11:54 UTC, wereldjes commented on functions/datalayer/UserDB.php
> +<?php
prepared statements

2020-05-12 11:54 UTC, wereldjes commented on functions/models/EntAxis.php
> +<?php
whitespaces

2020-05-12 11:54 UTC, wereldjes commented on functions/models/entUser.php
> +<?php
2 user models ?

2020-05-12 11:55 UTC, wereldjes commented
volgende keer ook wat kleinere pull requests pls

2020-05-12 11:55 UTC, closed without merging